services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/app/backend
    working_dir: /app/backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    command:
      - sh
      - -c
      - |
          until psql postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:$POSTGRES_PORT/$POSTGRES_DB -c '\q' 2>/dev/null; do
            echo "⏳ Waiting for Postgres..."
            sleep 1
          done
          echo "✅ Postgres is ready"
          python manage.py runserver 0.0.0.0:8000
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    command: npm run dev

  postgres:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: doguser
      POSTGRES_PASSWORD: dogpass
      POSTGRES_DB: dogroulette
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  node_modules:
  postgres_data:
