services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
      - ./requirements.txt:/app/requirements.txt
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    command: npm run dev

volumes:
  node_modules: