[tool.ruff]
line-length = 100
target-version = "py311"

# Enable these rule sets (can be adjusted)
lint.select = [
  "E",    # pycodestyle errors
  "F",    # pyflakes
  "I",    # isort
  "UP",   # pyupgrade
  "B",    # bugbear
  "N",    # pep8-naming
]
lint.ignore = ["B008"]

# Fix automatically when possible
fix = true
unsafe-fixes = true

# Exclude virtualenv, alembic, cache, etc.
exclude = ["venv", "__pycache__", "alembic/versions"]

# You can override settings like this
[tool.ruff.lint.isort]
known-first-party = ["backend"]
