"""initial

Revision ID: a364f5f8db79
Revises: 
Create Date: 2025-06-13 03:37:57.111671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a364f5f8db79'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pet_petfinder_id'), table_name='pet')
    op.drop_table('pet')
    op.drop_index(op.f('ix_shelter_petfinder_id'), table_name='shelter')
    op.drop_table('shelter')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shelter',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('shelter_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('petfinder_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='shelter_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_shelter_petfinder_id'), 'shelter', ['petfinder_id'], unique=True)
    op.create_table('pet',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('petfinder_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('age', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('size', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('breed', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('photos', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('published_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('shelter_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['shelter_id'], ['shelter.id'], name=op.f('pet_shelter_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('pet_pkey'))
    )
    op.create_index(op.f('ix_pet_petfinder_id'), 'pet', ['petfinder_id'], unique=True)
    # ### end Alembic commands ###
