"""initial migration

Revision ID: bca921c5d413
Revises:
Create Date: 2025-06-14 14:55:51.817551

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "bca921c5d413"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shelter",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("petfinder_id", sa.Integer(), nullable=False),
        sa.Column("last_updated", sa.DateTime(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("city", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("state", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("country", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_shelter_petfinder_id"),
        "shelter",
        ["petfinder_id"],
        unique=True,
    )
    op.create_table(
        "pet",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("petfinder_id", sa.Integer(), nullable=False),
        sa.Column("last_updated", sa.DateTime(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("age", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("gender", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("size", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("breed", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("photos", sa.JSON(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column("shelter_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["shelter_id"],
            ["shelter.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pet_petfinder_id"), "pet", ["petfinder_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pet_petfinder_id"), table_name="pet")
    op.drop_table("pet")
    op.drop_index(op.f("ix_shelter_petfinder_id"), table_name="shelter")
    op.drop_table("shelter")
    # ### end Alembic commands ###
