# Generated by Django 5.2.3 on 2025-06-15 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("age", models.CharField(blank=True, default="", max_length=50)),
                ("gender", models.CharField(blank=True, default="", max_length=50)),
                ("size", models.CharField(blank=True, default="", max_length=50)),
                ("breed", models.CharField(blank=True, default="", max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("photos", models.JSONField(blank=True, null=True)),
                ("status", models.CharField(blank=True, default="", max_length=50)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
